apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-app-deploy
  labels:
    app: easy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easy-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: easy-app
    spec:
      containers:
        - image: ykankane/easy_app:v1
          name: easy-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http-server

---


apiVersion: v1
kind: Service
metadata:
  name: easy-app-service
spec:
  selector:
    app: easy-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80