
version: 2
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
        # auth:
        #   username: $DOCUSER
        #   password: $DOCPASS

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      # - setup_remote_docker:
      #     version: 20.10.2

      - run:
          name: build image
          command: |
            apt-get install docker-cli
            docker build --tag=ykankane/easy_app:v1 .
            docker image ls

      - run:
          name: push image
          command: |
            echo $DOCPASS | docker login --username $DOCUSER --password-stdin
            docker push ykankane/easy_app:v1