
version: 2.1
jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O ./hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x ./hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint


  build:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7-alpine3.11

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            apk add --update docker-cli
            dockerd

      - run:
          name: build image
          command: |
            docker build --tag=ykankane/easy_app:v1 .
            docker image ls

      - run:
          name: push image
          command: |
            echo $DOCPASS | docker login --username $DOCUSER --password-stdin
            docker push ykankane/easy_app:v1

workflows:
  default:
    jobs:
      - lint
      - build:
          requires: [lint]